
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
public class guilhotina extends javax.swing.JFrame {

    //variaveis
    boolean controladorfinal = true;
  boolean controladorl [] = new boolean [5];
    int b = 0;
    String a = null;
     public guilhotina() {
        initComponents();
        numaleatorio();
        lamina3.setVisible(false);
           
           lamina2.setVisible(false);
           lamina5.setVisible(false);
           cabecam.setVisible(false);
           lamina4.setVisible(false);
        

    }

    private void acertou() {
        if (this.b < 12){
        this.b++;
        this.a = " " + this.b;
        valorscore.setText(a);
        controlador = false;
        invisivel();
        }
        else {
            new Ganhou().setVisible(true);
        }
        

    }

    private void errou() {
       
        if (controladorl [0] == false){
          
           lamina2.setVisible(true);
           lamina.setVisible(false);
           controladorl [0] = true;
           }
       else if (controladorl [1] == false){
           lamina3.setVisible(true);
           lamina2.setVisible(false);
           controladorl [1] = true;
       }
       else if (controladorl [2] == false){
            lamina4.setVisible(true);
           lamina3.setVisible(false);
           controladorl [2] = true;
           
       } 
       else if (controladorl[3] == false){
          lamina4.setVisible(false);
          lamina5.setVisible(true);
          controladorfinal = false;
           new perdeu().setVisible(true);
             this.setVisible(false);
       }
      
    }

    private void invisivel() {
        r1.setText("");
        r2.setText("");
        r3.setText("");
        r4.setText("");
        p1.setText("");
        controladorr[0] = false;
        controladorr[1] = false;
        controladorr[2] = false;
        controladorr[3] = false;
        controlador = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cabecav = new javax.swing.JLabel();
        cabecam = new javax.swing.JLabel();
        guilhotina = new javax.swing.JLabel();
        lamina5 = new javax.swing.JLabel();
        lamina3 = new javax.swing.JLabel();
        lamina2 = new javax.swing.JLabel();
        lamina = new javax.swing.JLabel();
        newp = new javax.swing.JLabel();
        r1 = new javax.swing.JLabel();
        r2 = new javax.swing.JLabel();
        r3 = new javax.swing.JLabel();
        r4 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        pedra1 = new javax.swing.JLabel();
        pedra2 = new javax.swing.JLabel();
        pedra3 = new javax.swing.JLabel();
        pedra4 = new javax.swing.JLabel();
        pedra5 = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        placa = new javax.swing.JLabel();
        valorscore = new javax.swing.JLabel();
        lamina4 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cabecav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cabecav.png"))); // NOI18N
        getContentPane().add(cabecav, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 110, 60));

        cabecam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cabecam.png"))); // NOI18N
        getContentPane().add(cabecam, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 140, 60));

        guilhotina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/guilhotinac.png"))); // NOI18N
        getContentPane().add(guilhotina, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, 230));

        lamina5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/laminac.png"))); // NOI18N
        getContentPane().add(lamina5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, -1, 50));

        lamina3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/laminac.png"))); // NOI18N
        getContentPane().add(lamina3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        lamina2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/laminac.png"))); // NOI18N
        getContentPane().add(lamina2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        lamina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/laminac.png"))); // NOI18N
        lamina.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(lamina, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, 70));
        lamina.getAccessibleContext().setAccessibleDescription("");

        newp.setForeground(new java.awt.Color(255, 255, 255));
        newp.setText("Próxima pergunta");
        newp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newpMouseClicked(evt);
            }
        });
        newp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                newpKeyPressed(evt);
            }
        });
        getContentPane().add(newp, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, -1, 10));

        r1.setForeground(new java.awt.Color(255, 255, 255));
        r1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r1MouseClicked(evt);
            }
        });
        getContentPane().add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        r2.setForeground(new java.awt.Color(255, 255, 255));
        r2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r2MouseClicked(evt);
            }
        });
        getContentPane().add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, -1, -1));

        r3.setForeground(new java.awt.Color(255, 255, 255));
        r3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r3MouseClicked(evt);
            }
        });
        getContentPane().add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        r4.setForeground(new java.awt.Color(255, 255, 255));
        r4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r4MouseClicked(evt);
            }
        });
        getContentPane().add(r4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, -1, -1));

        p1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        pedra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pedra.png"))); // NOI18N
        getContentPane().add(pedra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        pedra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pedra.png"))); // NOI18N
        getContentPane().add(pedra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, -1));

        pedra3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pedra.png"))); // NOI18N
        getContentPane().add(pedra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        pedra4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pedra.png"))); // NOI18N
        getContentPane().add(pedra4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, -1));

        pedra5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pedra.png"))); // NOI18N
        getContentPane().add(pedra5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, -1, -1));

        score.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        score.setForeground(new java.awt.Color(255, 255, 255));
        score.setText("Score:");
        getContentPane().add(score, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        placa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/placac.png"))); // NOI18N
        placa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                placaMouseClicked(evt);
            }
        });
        getContentPane().add(placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, -1));

        valorscore.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valorscore.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(valorscore, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 8, 20, 20));

        lamina4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/laminac.png"))); // NOI18N
        getContentPane().add(lamina4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 810, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void placaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_placaMouseClicked
    }//GEN-LAST:event_placaMouseClicked

    private void newpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newpKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpKeyPressed
    boolean controlador = false;
    int e = 0;
    private void newpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newpMouseClicked
        if (controlador == false && controladorfinal == true) {
            perguntas(e);
            e++;
            controlador = true;

        } else if (controlador == true){
            new erro().setVisible(true);

        }
    }//GEN-LAST:event_newpMouseClicked

    private void r4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r4MouseClicked
        if (controladorr[3] == false) {
            errou();
            invisivel();
        } else {
            acertou();
            invisivel();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_r4MouseClicked

    private void r1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r1MouseClicked
        if (controladorr[0] == false) {
            errou();
            invisivel();
        } else {
            acertou();
            invisivel();
        }
    }//GEN-LAST:event_r1MouseClicked

    private void r2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r2MouseClicked
        if (controladorr[1] == false) {
            errou();
            invisivel();
        } else {
            acertou();
            invisivel();
        }
    }//GEN-LAST:event_r2MouseClicked

    private void r3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r3MouseClicked
        if (controladorr[2] == false) {
            errou();
            invisivel();
        } else {
            acertou();
            invisivel();
        }
    }//GEN-LAST:event_r3MouseClicked

    boolean controladorr[] = new boolean[4];

    private void perguntas(int q) {
        switch (num[q]) {
            case 1:
            p1.setText("O evento da fuga de Maomé chama-se:");
                r1.setText("Hégira");
                r2.setText("Êxodo");
                r3.setText("Diaspora");
                r4.setText("Expulsao de Maomé");
                controladorr[0] = true;
                break;
                case 2:
                p1.setText("Arcanjo que conversou com Maomé:");
                r1.setText("Arcanjo Leonardo");
                r2.setText("Arcanjo Miguel");
                r3.setText("Arcanjo Gabriel");
                r4.setText("Arcanjo Lúcifer");
                controladorr[2] = true;
                break;
                case 3:
                p1.setText("Regiao onde fica Esparta:");
                r1.setText("Peninsula Ibérica");
                r2.setText("Peloponeso");
                r3.setText("Magna Grécia");
                r4.setText("Ásia");
                controladorr[1] = true;
                break;
                case 4:
                p1.setText("Número de cruzadas oficiais:");
                r1.setText("7");
                r2.setText("6");
                r3.setText("9");
                r4.setText("8");
                controladorr[3] = true;
                break;
                case 5:
                p1.setText("Caracteristca do estilo Gótico:");
                r1.setText("Pouco enfeite");
                r2.setText("Pouca iluminação");
                r3.setText("Arcos semicirculares");
                r4.setText("Arcos 'quebrados' ");
                controladorr[3] = true;
                break;
                case 6:
                p1.setText("Qual não é Característica de uma Crônica:");
                r1.setText("Problemas do Cotidiano");
                r2.setText("Normalmente longo");
                r3.setText("Tenta envolver o leitor");
                r4.setText("Todas são");
                controladorr[1] = true;
                break;
                case 7:
                p1.setText("Duração (geralmente) do ciclo Menstrual:");
                r1.setText("26");
                r2.setText("27");
                r3.setText("24");
                r4.setText("28");
                controladorr[3] = true;
                break;
                case 8:
                p1.setText("Qual não é um Glandula anexa:");
                r1.setText("Epididimo");
                r2.setText("Prostata");
                r3.setText("Vesicula Seminal");
                r4.setText("Glandula bulboretral");
                controladorr[0] = true;
                break;
                case 9:
                p1.setText("A Membrana Plasmática é:");
                r1.setText("Permeavel");
                r2.setText("Semipermeavel");
                r3.setText("Impermeavel");
                r4.setText("Nenhuma das anteriores");
                controladorr[1] = true;
                break;
               
                case 10:
                p1.setText("O nome de um conjunto é escrito com:");
                r1.setText("Números reais");
                r2.setText("Numeros complexos");
                r3.setText("Letras maiuscula");
                r4.setText("Letras minuscula");
                controladorr[2] = true;
                break;
                case 11:
                p1.setText("É possivel representar um conjunto com:");
                r1.setText("Diagrama de Vehn");
                r2.setText("Diagrama de Pitagoras");
                r3.setText("Diagrama do Pablo");
                r4.setText("Diagrama de Venn");
                controladorr[0] = true;
                break;
                case 12:
                p1.setText("1/5 é igual a:");
                r1.setText("0,5");
                r2.setText("0,3");
                r3.setText("0,2");
                r4.setText("0,25");
                controladorr[2] = true;
                break;
                
                case 13:
                p1.setText("6 . 8 é:");
                r1.setText("48");
                r2.setText("32");
                r3.setText("64");
                r4.setText("36");
                controladorr[0] = true;
                break;
                case 14:
                p1.setText("É substantivo de dois numeros:");
                r1.setText("Branco");
                r2.setText("Artista");
                r3.setText("Jovem");
                r4.setText("Lápis");
                controladorr[3] = true;
                break;
                case 15:
                p1.setText("100mm é igual a:");
                r1.setText("1 metro");
                r2.setText("1 centimetro");
                r3.setText("10 centimetros");
                r4.setText("10 decimetros");
                controladorr[2] = true;
                break;
                
                case 16:
                p1.setText("1 decimetro cubico é igual a:");
                r1.setText("10ml");
                r2.setText("100ml");
                r3.setText("1 litro");
                r4.setText("0,5 litros");
                controladorr[2] = true;
                break;
                case 17:
                p1.setText("Formula do Gelo Seco");
                r1.setText("CO4");
                r2.setText("CO");
                r3.setText("CO3");
                r4.setText("CO2");
                controladorr[3] = true;
                break;
                case 18:
                p1.setText("O ponto de fusão da água em 1atm é:");
                r1.setText("0 graus");
                r2.setText("50 graus");
                r3.setText("100 graus");
                r4.setText("Nenhuma das anteriores");
                controladorr[0] = true;
                break;
                case 19:
                p1.setText("O estado físico do Hélio no Sol é:");
                r1.setText("Gasoso");
                r2.setText("Plasma");
                r3.setText("Não há Hélio no sol");
                r4.setText("Nenhuma das anteriores");
                controladorr[1] = true;
                break;
                case 20:
                p1.setText("Qual o tipo de vaporização mais rápido:");
                r1.setText("Evaporação");
                r2.setText("Calefação");
                r3.setText("Ebulição");
                r4.setText("Nenhuma das anteriores");
                controladorr[1] = true;
                break;
                
                
                    

           

        }

    }

    int numero;
    int[] num = {
            1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
        };
    private void numaleatorio() {
 Random r = new Random();
        
        for (int i = 0; i < (num.length - 1); i++) {
            int j = r.nextInt(num.length);
            int temp = num[i];
            num[i] = num[j];
            num[j] = temp;
        }
        

        

        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guilhotina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guilhotina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guilhotina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guilhotina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guilhotina().setVisible(true);
                

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel cabecam;
    private javax.swing.JLabel cabecav;
    private javax.swing.JLabel guilhotina;
    private javax.swing.JLabel lamina;
    private javax.swing.JLabel lamina2;
    private javax.swing.JLabel lamina3;
    private javax.swing.JLabel lamina4;
    private javax.swing.JLabel lamina5;
    private javax.swing.JLabel newp;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel pedra1;
    private javax.swing.JLabel pedra2;
    private javax.swing.JLabel pedra3;
    private javax.swing.JLabel pedra4;
    private javax.swing.JLabel pedra5;
    private javax.swing.JLabel placa;
    private javax.swing.JLabel r1;
    private javax.swing.JLabel r2;
    private javax.swing.JLabel r3;
    private javax.swing.JLabel r4;
    private javax.swing.JLabel score;
    private javax.swing.JLabel valorscore;
    // End of variables declaration//GEN-END:variables
}
