
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Artur
 */
public class Fogueira extends javax.swing.JFrame {

    /**
     * Creates new form Fogueira
     */
    public Fogueira() {
        initComponents();
        fogo1.setVisible(false);
        fogo2.setVisible(false);
        fogo3.setVisible(false);
        numaleatorio();
        invisivel();
        cabecam.setVisible(false);
    }
//variaveis
     int e = 0;
    int numero;
int[] num = {
            1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
        };
 boolean controladorr[] = new boolean[4];
 int b = 0;
 String a = null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fogo1 = new javax.swing.JLabel();
        fogo2 = new javax.swing.JLabel();
        fogo3 = new javax.swing.JLabel();
        cabecam = new javax.swing.JLabel();
        personagem = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        r3 = new javax.swing.JLabel();
        r1 = new javax.swing.JLabel();
        r2 = new javax.swing.JLabel();
        r4 = new javax.swing.JLabel();
        newp = new javax.swing.JLabel();
        pedra2 = new javax.swing.JLabel();
        pedra1 = new javax.swing.JLabel();
        pedra3 = new javax.swing.JLabel();
        pedra4 = new javax.swing.JLabel();
        placa = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        valorscore = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fogo1.png"))); // NOI18N
        getContentPane().add(fogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, 140));

        fogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fogo2.png"))); // NOI18N
        getContentPane().add(fogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 350, 200));

        fogo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fogo3c.png"))); // NOI18N
        getContentPane().add(fogo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        cabecam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cabecam.png"))); // NOI18N
        getContentPane().add(cabecam, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 239, 140, 70));

        personagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/personagemc.png"))); // NOI18N
        getContentPane().add(personagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, 370));

        p1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        r3.setForeground(new java.awt.Color(255, 255, 255));
        r3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r3MouseClicked(evt);
            }
        });
        getContentPane().add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        r1.setForeground(new java.awt.Color(255, 255, 255));
        r1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r1MouseClicked(evt);
            }
        });
        getContentPane().add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, -1));

        r2.setForeground(new java.awt.Color(255, 255, 255));
        r2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r2MouseClicked(evt);
            }
        });
        getContentPane().add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, -1, -1));

        r4.setForeground(new java.awt.Color(255, 255, 255));
        r4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r4MouseClicked(evt);
            }
        });
        getContentPane().add(r4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, -1, -1));

        newp.setForeground(new java.awt.Color(255, 255, 255));
        newp.setText("Próxima Pergunta");
        newp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newpMouseClicked(evt);
            }
        });
        getContentPane().add(newp, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, -1, -1));

        pedra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pedra.png"))); // NOI18N
        getContentPane().add(pedra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 200, 70));

        pedra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pedra.png"))); // NOI18N
        getContentPane().add(pedra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 210, 70));

        pedra3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pedra.png"))); // NOI18N
        getContentPane().add(pedra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 200, 70));

        pedra4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pedra.png"))); // NOI18N
        getContentPane().add(pedra4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 210, 70));

        placa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/placac.png"))); // NOI18N
        getContentPane().add(placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 300, -1));

        score.setForeground(new java.awt.Color(255, 255, 255));
        score.setText("Score:");
        getContentPane().add(score, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        valorscore.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(valorscore, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pedra.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 210, 70));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 800, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents
boolean controlador = false;
boolean controladorfim = true;
    private void newpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newpMouseClicked
     if (controlador == false && controladorfim == true) {
            perguntas(e);
            e++;
            controlador = true;
        } else if (controlador == true) {
            
            new erro().setVisible(true);
        }


                                     
    }//GEN-LAST:event_newpMouseClicked

    private void r1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r1MouseClicked
       if (controladorr[0] == true) {
            acertou();
        } else {
            errou();
        }
        controlador = false;
    }//GEN-LAST:event_r1MouseClicked

    private void r2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r2MouseClicked
      if (controladorr[1] == true) {
            acertou();
        } else {
            errou();
        }
        controlador = false;
    }//GEN-LAST:event_r2MouseClicked

    private void r3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r3MouseClicked
       if (controladorr[2] == true) {
            acertou();
        } else {
            errou();
        }
        controlador = false;
    }//GEN-LAST:event_r3MouseClicked

    private void r4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r4MouseClicked
        if (controladorr[3] == true) {
            acertou();
        } else {
            errou();
        }
        controlador = false;
    }//GEN-LAST:event_r4MouseClicked

    private void numaleatorio() {
 Random r = new Random();
        
        for (int i = 0; i < (num.length - 1); i++) {
            int j = r.nextInt(num.length);
            int temp = num[i];
            num[i] = num[j];
            num[j] = temp;
        }
        


        
    }
    
     boolean[] controladorimg = new boolean[3];

    private void errou() {
        if (controladorimg[0] == false) {
            fogo1.setVisible(true);
            controladorimg[0] = true;
        } else if (controladorimg[1] == false) {
            fogo2.setVisible(true);
            controladorimg[1] = true;
        } else if (controladorimg[2] == false) {
       
            fogo3.setVisible(true);
            controladorimg[2] = true;
            new perdeu().setVisible(true);
            controladorfim = false;
            cabecam.setVisible(true);
             this.setVisible(false);
        }
      
        invisivel();

    }
     private void perguntas(int q) {
        switch (num[q]) {
            case 1:
                p1.setText("Qual não é um Substantivo Derivado");
                r1.setText("Ferreiro");
                r2.setText("Sapateiro");
                r3.setText("Pedreiro");
                r4.setText("Todos são");
                controladorr[3] = true;
                break;
                case 2:
                p1.setText("Descobriu a ilha de Porto santo:");
                r1.setText("Pedro Alvares Cabral");
                r2.setText("Bartolomeu Dias");
                r3.setText("João Gonçalves");
                r4.setText("Vasco da Gama");
                controladorr[2] = true;
                break;
                case 3:
                p1.setText("Fundador da escola de Sagres:");
                r1.setText("Vasco da Gama");
                r2.setText("Henrique, o navegador");
                r3.setText("Pepino, o Breve");
                r4.setText("Bartolomeu Dias");
                controladorr[1] = true;
                break;
                case 4:
                p1.setText("Século que começou o declínio dos Feudos:");
                r1.setText("12");
                r2.setText("14");
                r3.setText("13");
                r4.setText("9");
                controladorr[2] = true;
                break;
                case 5:
                p1.setText("Duração da Guerra dos 100 anos:");
                r1.setText("100 anos");
                r2.setText("101 anos");
                r3.setText("113 anos");
                r4.setText("116 anos");
                controladorr[3] = true;
                break;
                case 6:
                p1.setText("Século do surgimento do Islamismo:");
                r1.setText("6");
                r2.setText("8");
                r3.setText("5");
                r4.setText("7");
                controladorr[3] = true;
                break;
                case 7:
                p1.setText("Principal livro sagrado do Islamismo:");
                r1.setText("Alcorão");
                r2.setText("Torá");
                r3.setText("Suna");
                r4.setText("Bíblia");
                controladorr[0] = true;
                break;
                case 8:
                p1.setText("Autor de 'Os Lusíadas':");
                r1.setText("Machado de Assis");
                r2.setText("Eça de Queiroz");
                r3.setText("Luís Vaz de Camões");
                r4.setText("Fernando Pessoa");
                controladorr[2] = true;
                break;
                case 9:
                p1.setText("Assunto da obra 'Os Lusíadas':");
                r1.setText("Império Romano");
                r2.setText("Vikings");
                r3.setText("Mitologia");
                r4.setText("Nenhuma das anteriores");
                controladorr[3] = true;
                break;
                case 10:
                p1.setText("Antônimo de 'meritório':");
                r1.setText("Diligente");
                r2.setText("Medroso");
                r3.setText("Indigno");
                r4.setText("Nenhuma das anteriores");
                controladorr[2] = true;
                break;
                case 11:
                p1.setText("Jatinho é Hipônimo de:");
                r1.setText("Avião");
                r2.setText("Piloto");
                r3.setText("Aeroporto");
                r4.setText("Pista");
                controladorr[0] = true;
                break;
                case 12:
                p1.setText("Papagaio é Hipônimo de:");
                r1.setText("Gaivota");
                r2.setText("Coruja");
                r3.setText("Ave");
                r4.setText("Nenhum das anteriores");
                controladorr[2] = true;
                break;
                case 13:
                p1.setText("Xadrez é Hipônimo de:");
                r1.setText("Jogo");
                r2.setText("Rainha");
                r3.setText("Estratégia");
                r4.setText("Nenhuma das anteriores");
                controladorr[0] = true;
                break;
                 case 14:
                p1.setText("Fórmula da Glicose:");
                r1.setText("C6H12O6");
                r2.setText("C3H12HO3");
                r3.setText("C6H3C6");
                r4.setText("C6H10C6");
                controladorr[0] = true;
                break;
                case 15:
                p1.setText("Fórmula do sal de cozinha:");
                r1.setText("Cl");
                r2.setText("KNA");
                r3.setText("Cl2");
                r4.setText("ClNa");
                controladorr[3] = true;
                break;
                case 16:
                p1.setText("25 cm é igual a:");
                r1.setText("2,5 decimetros");
                r2.setText("0,2 metros");
                r3.setText("2500 mm");
                r4.setText("Nenhuma das anteriores");
                controladorr[0] = true;
                break;
                case 17:
                p1.setText("0,111... é igual a:");
                r1.setText("1/10");
                r2.setText("1/9");
                r3.setText("1/7");
                r4.setText("Nenhum das anteriores");
                controladorr[1] = true;
                break;
                 case 18:
                p1.setText("Qual não faz parte de um cromossomo:");
                r1.setText("Centrômero");
                r2.setText("Cromatídes");
                r3.setText("Protase");
                r4.setText("Telômero");
                controladorr[2] = true;
                break;
                case 19:
                p1.setText("Qual não é biomolécula?");
                r1.setText("Proteína");
                r2.setText("Lipídio");
                r3.setText("DNA");
                r4.setText("Todos são");
                controladorr[2] = true;
                break;
                case 20:
                p1.setText("Qual o cosseno de um ângulo de 60 graus");
                r1.setText("2/2");
                r2.setText("3/2");
                r3.setText("1/2");
                r4.setText("1");
                controladorr[2] = true;
                break;
               
                
                
        }
     }
     private void acertou() {

        if (b < 14) {
            this.b++;
            this.a = " " + this.b;
            valorscore.setText(a);
        } else {
            this.setVisible(false);
            new Ganhou().setVisible(true);
        }
invisivel();
    }
     
      private void invisivel() {
        p1.setText(" ");
        r1.setText(" ");
        r2.setText(" ");
        r3.setText(" ");
        r4.setText(" ");
        controladorr[0] = false;
        controladorr[1] = false;
        controladorr[2] = false;
        controladorr[3] = false;
        controlador = false;

    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fogueira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fogueira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fogueira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fogueira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fogueira().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel cabecam;
    private javax.swing.JLabel fogo1;
    private javax.swing.JLabel fogo2;
    private javax.swing.JLabel fogo3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel newp;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel pedra1;
    private javax.swing.JLabel pedra2;
    private javax.swing.JLabel pedra3;
    private javax.swing.JLabel pedra4;
    private javax.swing.JLabel personagem;
    private javax.swing.JLabel placa;
    private javax.swing.JLabel r1;
    private javax.swing.JLabel r2;
    private javax.swing.JLabel r3;
    private javax.swing.JLabel r4;
    private javax.swing.JLabel score;
    private javax.swing.JLabel valorscore;
    // End of variables declaration//GEN-END:variables
}
