
import java.util.Random;
import javax.swing.JLabel;

public class jogo extends javax.swing.JFrame {

    /**
     * Creates new form jogo
     */
    public jogo() {
        initComponents();
        numaleatorio();

        cabeca.setVisible(false);
        tronco.setVisible(false);
        bracoe.setVisible(false);
        bracod.setVisible(false);
        pernae.setVisible(false);
        pernad.setVisible(false);
        cabecam.setVisible(false);

    }
    int b = 0;
    String a = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        score = new javax.swing.JLabel();
        valorscore = new javax.swing.JLabel();
        r1 = new javax.swing.JLabel();
        r2 = new javax.swing.JLabel();
        r3 = new javax.swing.JLabel();
        r4 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        newp2 = new javax.swing.JLabel();
        cabecam = new javax.swing.JLabel();
        cabeca = new javax.swing.JLabel();
        forca = new javax.swing.JLabel();
        tronco = new javax.swing.JLabel();
        bracoe = new javax.swing.JLabel();
        bracod = new javax.swing.JLabel();
        pernad = new javax.swing.JLabel();
        pernae = new javax.swing.JLabel();
        pedra1 = new javax.swing.JLabel();
        pedra2 = new javax.swing.JLabel();
        pedra4 = new javax.swing.JLabel();
        pedra3 = new javax.swing.JLabel();
        pedra5 = new javax.swing.JLabel();
        placa = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        score.setForeground(new java.awt.Color(255, 255, 255));
        score.setText("Score:");
        getContentPane().add(score, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 40, 20));

        valorscore.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(valorscore, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 20, 20));

        r1.setForeground(new java.awt.Color(255, 255, 255));
        r1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r1MouseClicked(evt);
            }
        });
        getContentPane().add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        r2.setForeground(new java.awt.Color(255, 255, 255));
        r2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r2MouseClicked(evt);
            }
        });
        getContentPane().add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, -1, -1));

        r3.setForeground(new java.awt.Color(255, 255, 255));
        r3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r3MouseClicked(evt);
            }
        });
        getContentPane().add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, -1));

        r4.setForeground(new java.awt.Color(255, 255, 255));
        r4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r4MouseClicked(evt);
            }
        });
        getContentPane().add(r4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));

        p1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        newp2.setForeground(new java.awt.Color(255, 255, 255));
        newp2.setText("Próxima Pergunta");
        newp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newp2MouseClicked(evt);
            }
        });
        getContentPane().add(newp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, -1, 10));

        cabecam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cabecam.png"))); // NOI18N
        getContentPane().add(cabecam, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 110, 70));

        cabeca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cabecav.png"))); // NOI18N
        getContentPane().add(cabeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 110, 120));

        forca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/forcac.png"))); // NOI18N
        getContentPane().add(forca, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, 260));

        tronco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tronco.png"))); // NOI18N
        getContentPane().add(tronco, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        bracoe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bracoe.png"))); // NOI18N
        getContentPane().add(bracoe, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        bracod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bracod.png"))); // NOI18N
        getContentPane().add(bracod, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 90, 110));

        pernad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perna.png"))); // NOI18N
        getContentPane().add(pernad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        pernae.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pernaee.png"))); // NOI18N
        getContentPane().add(pernae, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        pedra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pedra.png"))); // NOI18N
        getContentPane().add(pedra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 200, 80));

        pedra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pedra.png"))); // NOI18N
        getContentPane().add(pedra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 200, 90));

        pedra4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pedra.png"))); // NOI18N
        pedra4.setToolTipText("");
        getContentPane().add(pedra4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, -1));

        pedra3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pedra.png"))); // NOI18N
        getContentPane().add(pedra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        pedra5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pedra.png"))); // NOI18N
        pedra5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pedra5MouseClicked(evt);
            }
        });
        getContentPane().add(pedra5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 200, 70));

        placa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/placac.png"))); // NOI18N
        getContentPane().add(placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 810, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents
boolean controlador = false;
boolean controladorfim = true;
    private void newp2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newp2MouseClicked
        if (controlador == false && controladorfim == true) {
            perguntas(e);
            e++;
            controlador = true;
        } else if (controlador == true) {
            
            new erro().setVisible(true);
        }


    }//GEN-LAST:event_newp2MouseClicked
    int e = 0;
    int numero;
int[] num = {
            1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
        };
    private void numaleatorio() {
 Random r = new Random();
        
        for (int i = 0; i < (num.length - 1); i++) {
            int j = r.nextInt(num.length);
            int temp = num[i];
            num[i] = num[j];
            num[j] = temp;
        }
        

       

        
    }
    boolean[] controladorimg = new boolean[6];

    private void errou() {
        if (controladorimg[0] == false) {
            cabeca.setVisible(true);
            controladorimg[0] = true;
        } else if (controladorimg[1] == false) {
            tronco.setVisible(true);
            controladorimg[1] = true;
        } else if (controladorimg[2] == false) {
            bracoe.setVisible(true);
            controladorimg[2] = true;
        } else if (controladorimg[3] == false) {
            bracod.setVisible(true);
            controladorimg[3] = true;
        } else if (controladorimg[4] == false) {
            pernae.setVisible(true);
            controladorimg[4] = true;
        } else if (controladorimg[5] == false) {
            pernad.setVisible(true);
            controladorimg[5] = true;
            new perdeu().setVisible(true);
            controladorfim = false;
            this.setVisible(false);
         
        }
      
        invisivel();

    }
    boolean controladorr[] = new boolean[4];

    private void perguntas(int q) {
        switch (num[q]) {
            case 1:
                p1.setText("Primerio navegador a ir para a Índia:");
                r1.setText("Gil Eanes");
                r2.setText("Pedro Alvares Cabral");
                r3.setText("Cristovão Colombo");
                r4.setText("Vasco da Gama");
                controladorr[3] = true;
                break;

            case 2:
                p1.setText("Ano que terminou a Idade Média:");
                r1.setText("1453");
                r2.setText("1476");
                r3.setText("1452");
                r4.setText("1477");
                controladorr[0] = true;
                break;
                 case 3:
                p1.setText("Ano que começou a Idade Média:");
                r1.setText("452");
                r2.setText("475");
                r3.setText("476");
                r4.setText("482");
                controladorr[2] = true;
                break;
                case 4:
                p1.setText("Onde Maomé se Refugiou:");
                r1.setText("Meca");
                r2.setText("Medina");
                r3.setText("Kush");
                r4.setText("Punt");
                controladorr[1] = true;
                break;
                case 5:
                p1.setText("Qual não é um método contraceptivo:");
                r1.setText("Pilula");
                r2.setText("DIU");
                r3.setText("Diafragma");
                r4.setText("Todos são");
                controladorr[3] = true;
                break;
                case 6:
                p1.setText("Fórmula do Teorema de Pitagoras:");
                r1.setText("a² = b² + c²");
                r2.setText("a = b + c");
                r3.setText("a² = b + c");
                r4.setText("a = b² + c2");
                controladorr[0] = true;
                break;
                case 7:
                p1.setText("Fórmula de uma Função Afim:");
                r1.setText("f(x)= ax - b");
                r2.setText("f(x)= a - bx");
                r3.setText("f(x)= ax + b");
                r4.setText("f(x)= a + bx");
                controladorr[2] = true;
                break;
                case 8:
                p1.setText("Fórmula de uma Função Quadrática:");
                r1.setText("f(x)= ax + b²");
                r2.setText("f(x)= ax² + bx + c");
                r3.setText("f(x)= ax + bx + c²");
                r4.setText("f(x) = a²");
                controladorr[1] = true;
                break;
                case 9:
                p1.setText("10 . 12 + 3 é:");
                r1.setText("123");
                r2.setText("120");
                r3.setText("150");
                r4.setText("130");
                controladorr[0] = true;
                break;
                case 10:
                p1.setText("'Amor maternal' é um(a):");
                r1.setText("Substantivo Comum");
                r2.setText("Locução Adjetiva");
                r3.setText("Adjetivo Primitivo");
                r4.setText("Adjetivo Composto");
                    controladorr[1] = true;
                break;
                case 11:
                p1.setText("Qual desses tem célula procarionte:");
                r1.setText("Plantas");
                r2.setText("Fungos");
                r3.setText("Protistas");
                r4.setText("Bactérias");
                controladorr[3] = true;
                break;
                case 12:
                p1.setText("Qual não é um mecanismo de transporte:");
                r1.setText("Difusão");
                r2.setText("Osmose");
                r3.setText("ATP");
                r4.setText("Transporte Ativo");
                controladorr[2] = true;
                break;
                case 13:
                p1.setText("Qual não existia na Atmosfera Primitiva:");
                r1.setText("lítio");
                r2.setText("Amônia");
                r3.setText("Hidrogênio");
                r4.setText("Metano");
                controladorr[0] = true;
                break;
                case 14:
                p1.setText("Primeira lei de Newton:");
                r1.setText("Ação e Reação");
                r2.setText("Gravidade");
                r3.setText("Inércia");
                r4.setText("Principio da dinamica");
                controladorr[2] = true;
                break;
                case 15:
                p1.setText("Equação de Torricelli");
                r1.setText("Vf = Vo + 2a.Δs");
                r2.setText("Vf² = Vo² + 2a.Δs");
                r3.setText("Vo = Vf + 2a.Δs");
                r4.setText("Vo² = Vf + 2a.Δs");
                controladorr[1] = true;
                break;
                 case 16:
                p1.setText("É substantivo sobrecomum:");
                r1.setText("Vítima");
                r2.setText("Estudante");
                r3.setText("Borboleta");
                r4.setText("Nenhuma das anteriores");
                controladorr[0] = true;
                break;
                 case 17:
                p1.setText("Seno de um angulo de 30 graus:");
                r1.setText("3/2");
                r2.setText("2/2");
                r3.setText("1/2");
                r4.setText("2/2");
                controladorr[2] = true;
                break;
                case 18:
                p1.setText("Simbolo do Fósforo:");
                r1.setText("S");
                r2.setText("F");
                r3.setText("P");
                r4.setText("K");
                controladorr[2] = true;
                break;
                case 19:
                p1.setText("Simbolo do Potássio:");
                r1.setText("P");
                r2.setText("Na");
                r3.setText("K");
                r4.setText("Be");
                controladorr[2] = true;
                break;
                case 20:
                p1.setText("Simbolo do Criptônio");
                r1.setText("Cr");
                r2.setText("Kr");
                r3.setText("Cu");
                r4.setText("Cs");
                controladorr[1] = true;
                break;
                
                               


        }

    }

    private void r4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r4MouseClicked
        if (controladorr[3] == true) {
            acertou();
        } else {
            errou();
        }
        controlador = false;
    }//GEN-LAST:event_r4MouseClicked

    private void r3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r3MouseClicked
        if (controladorr[2] == true) {
            acertou();
        } else {
            errou();
        }
        controlador = false;// TODO add your handling code here:
    }//GEN-LAST:event_r3MouseClicked

    private void pedra5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pedra5MouseClicked
      
    }//GEN-LAST:event_pedra5MouseClicked

    private void r2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r2MouseClicked
        if (controladorr[1] == true) {
            acertou();
        } else {
            errou();
        }
        controlador = false;
    }//GEN-LAST:event_r2MouseClicked

    private void r1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r1MouseClicked
        if (controladorr[0] == true) {
            acertou();
        } else {
            errou();
        }
        controlador = false;
    }//GEN-LAST:event_r1MouseClicked

   

    

    private void acertou() {

        if (b < 9) {
            this.b++;
            this.a = " " + this.b;
            valorscore.setText(a);
        } else {
            this.setVisible(false);
            new Ganhou().setVisible(true);
        }
invisivel();
    }

    private void invisivel() {
        p1.setText(" ");
        r1.setText(" ");
        r2.setText(" ");
        r3.setText(" ");
        r4.setText(" ");
        controladorr[0] = false;
        controladorr[1] = false;
        controladorr[2] = false;
        controladorr[3] = false;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel bracod;
    private javax.swing.JLabel bracoe;
    private javax.swing.JLabel cabeca;
    private javax.swing.JLabel cabecam;
    private javax.swing.JLabel forca;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel newp2;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel pedra1;
    private javax.swing.JLabel pedra2;
    private javax.swing.JLabel pedra3;
    private javax.swing.JLabel pedra4;
    private javax.swing.JLabel pedra5;
    private javax.swing.JLabel pernad;
    private javax.swing.JLabel pernae;
    private javax.swing.JLabel placa;
    private javax.swing.JLabel r1;
    private javax.swing.JLabel r2;
    private javax.swing.JLabel r3;
    private javax.swing.JLabel r4;
    private javax.swing.JLabel score;
    private javax.swing.JLabel tronco;
    private javax.swing.JLabel valorscore;
    // End of variables declaration//GEN-END:variables
}
